# Generated by Django 3.1.3 on 2021-03-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('route_long_name', models.CharField(max_length=200)),
                ('line_id', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('alternative', models.CharField(max_length=2)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.IntegerField()),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_desc', models.CharField(max_length=200)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('location_type', models.IntegerField()),
                ('parent_station', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('trip_headsign', models.CharField(max_length=100)),
                ('direction_id', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Stop_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('departure_time', models.CharField(max_length=8)),
                ('shape_dist_traveled', models.IntegerField()),
                ('actual_time', models.CharField(default=None, max_length=8, null=True)),
                ('accuracy', models.IntegerField(default=None, null=True)),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.stops')),
                ('trip_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times_trip_date', to='gtfs.trips')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times_trip_id', to='gtfs.trips')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trips',
            constraint=models.UniqueConstraint(fields=('trip_id', 'trip_date'), name='unique_trip'),
        ),
        migrations.AddConstraint(
            model_name='stop_times',
            constraint=models.UniqueConstraint(fields=('trip_id', 'trip_date', 'stop_sequence'), name='unique_stop_time'),
        ),
    ]
