# Generated by Django 3.1.3 on 2021-03-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='stop_times',
            name='stop_id',
        ),
        migrations.RemoveField(
            model_name='stop_times',
            name='trip_date',
        ),
        migrations.RemoveField(
            model_name='stop_times',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='route_id',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Stop_times',
        ),
        migrations.DeleteModel(
            name='Stops',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
